# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowtest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(260, 380)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_login = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_login.setGeometry(QtCore.QRect(30, 280, 200, 40))
        self.pushButton_login.setStyleSheet("#pushButton_login{\n"
"    selection-color: rgb(0, 170, 127);\n"
"    background-color:rgb(82, 156, 113);\n"
"    border-radius:20px;\n"
"    font: 16pt \"SentyTEA 新蒂下午茶体\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#pushButton_login{\n"
"    padding_top:20px;\n"
"}\n"
"")
        self.pushButton_login.setObjectName("pushButton_login")
        self.lineEditUser = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditUser.setGeometry(QtCore.QRect(60, 161, 160, 30))
        self.lineEditUser.setStyleSheet("border-radius:1px;\n"
"font: 9pt \"01FLOPDESIGN\";\n"
"color:rgb(59, 118, 87);")
        self.lineEditUser.setText("")
        self.lineEditUser.setObjectName("lineEditUser")
        self.lineEditPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPassword.setGeometry(QtCore.QRect(60, 212, 160, 30))
        self.lineEditPassword.setStyleSheet("border-radius:1px;\n"
"font: 9pt \"01FLOPDESIGN\";\n"
"color:rgb(59, 118, 87);")
        self.lineEditPassword.setText("")
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 50, 100, 100))
        self.label.setStyleSheet("background-image: url(:/image/resourse/头像（1）.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 260, 380))
        self.background.setStyleSheet("background-color: rgb(125, 200, 158);\n"
"border-radius:20px;")
        self.background.setText("")
        self.background.setObjectName("background")
        self.edit_background_1 = QtWidgets.QLabel(self.centralwidget)
        self.edit_background_1.setGeometry(QtCore.QRect(30, 160, 200, 32))
        self.edit_background_1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:15px")
        self.edit_background_1.setText("")
        self.edit_background_1.setObjectName("edit_background_1")
        self.edit_background_2 = QtWidgets.QLabel(self.centralwidget)
        self.edit_background_2.setGeometry(QtCore.QRect(30, 210, 200, 32))
        self.edit_background_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:15px")
        self.edit_background_2.setText("")
        self.edit_background_2.setObjectName("edit_background_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(36, 164, 20, 20))
        self.label_2.setStyleSheet("image: url(:/image/resourse/头像.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(36, 216, 20, 20))
        self.label_3.setStyleSheet("image: url(:/image/resourse/钥匙.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.Exit = QtWidgets.QPushButton(self.centralwidget)
        self.Exit.setGeometry(QtCore.QRect(223, 10, 26, 26))
        self.Exit.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 9pt \"01FLOPDESIGN\";")
        self.Exit.setObjectName("Exit")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(40, 250, 111, 18))
        self.checkBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")
        self.help = QtWidgets.QPushButton(self.centralwidget)
        self.help.setGeometry(QtCore.QRect(20, 340, 23, 23))
        self.help.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"background-image: url(:/image/resourse/帮助未按下.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-image: url(:/image/resourse/帮助按下.png);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"")
        self.help.setText("")
        self.help.setObjectName("help")
        self.setting = QtWidgets.QPushButton(self.centralwidget)
        self.setting.setGeometry(QtCore.QRect(215, 335, 28, 28))
        self.setting.setStyleSheet("QPushButton\n"
"{\n"
"border-radius:10px;\n"
"background-image: url(:/image/resourse/设置未按下.png);\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    background-image: url(:/image/resourse/设置按下.png);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"")
        self.setting.setText("")
        self.setting.setObjectName("setting")
        self.dialog = QtWidgets.QLabel(self.centralwidget)
        self.dialog.setGeometry(QtCore.QRect(30, 280, 200, 40))
        self.dialog.setStyleSheet("border-radius:20px;\n"
"background-image: url(:/image/resourse/dialog.gif);\n"
"")
        self.dialog.setText("")
        self.dialog.setObjectName("dialog")
        self.background.raise_()
        self.edit_background_2.raise_()
        self.edit_background_1.raise_()
        self.pushButton_login.raise_()
        self.lineEditUser.raise_()
        self.lineEditPassword.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.Exit.raise_()
        self.checkBox.raise_()
        self.help.raise_()
        self.setting.raise_()
        self.dialog.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Exit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_login.setText(_translate("MainWindow", "登录"))
        self.lineEditUser.setPlaceholderText(_translate("MainWindow", "user"))
        self.lineEditPassword.setPlaceholderText(_translate("MainWindow", "password"))
        self.Exit.setText(_translate("MainWindow", "X"))
        self.checkBox.setText(_translate("MainWindow", "记住账号密码"))
import resource_rc
